register/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate_account, name='activate'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^login_superuser/$', views.lgoin_superuser_view, name='login_superuser'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^logout_superuser/$', views.logout_superuser_view),
    url('signup_success/', views.signup_success, name='signup_success'),

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='register/password_change_done.html'), name='password_change_done'),
    path('pssword_change/', auth_views.PasswordChangeView.as_view(template_name='register/password_change.html'), name='password_change'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='register/password_reset_done.html'), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.PasswordResetConfirmView.as_view(template_name='register/password_reset_form.html'), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='register/password_reset.html'), name='password_reset'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='register/password_reset_complete.html'), name='password_reset_complete'),

]

worker/urls.py
from django.urls import path
from django.conf.urls import url

from . import views as worker_views

urlpatterns = [
    path('', worker_views.home, name='home'),
    path('dashboard/', worker_views.dashboard, name='dashboard'),
    path('purchase_instructions/', worker_views.purchase_instructions, name='purchase_instructions'),
    path('review_instructions/', worker_views.review_instructions, name='review_instructions'),
    path('tasks/', worker_views.claimed_tasks),
    path('payout/', worker_views.payouts),
    path('profile/', worker_views.profile, name='profile'),
    path('help/', worker_views.help),
    url(r'^claim_task/$', worker_views.claim, name='claim'),
    url(r'^payment_update/$', worker_views.payment_update, name='payment_update'),
    url(r'^upload_product_screenshot/$', worker_views.upload_product_screenshot, name='upload_product_screenshot'),
    url(r'^upload_review_screenshot/$', worker_views.upload_review_screenshot, name='upload_review_screenshot'), 
    url(r'^request_payout/$', worker_views.request_payout, name='request_payout'),
]

register/models.py
from django.db import models
from django.contrib.auth.models import User

User._meta.get_field('email')._unique = True

register/forms.py
from django import forms
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    email = forms.EmailField()

    class Meta:
        model = User   
        fields = ["username","first_name", "last_name", "email", "password1", "password2"]

register/views.py
import os
import json

from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from django.core.mail import send_mail
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.conf import settings
from django import forms


from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

from worker.models import Worker
from .forms import RegisterForm
from .support import get_client_ip, account_activation_token

def register(request):
    if request.method == "POST":
        ip = get_client_ip(request)
        current_site = get_current_site(request)
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            worker = Worker(
                user = user,
                used_ips = ip,
                order_notification = False,
            )
            # worker.save()
            email_subject = 'Activate Your Account'
            message = render_to_string('register/activate_account.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(email_subject, message, to=[to_email])
            email.send()
            worker.save()
            return HttpResponse('Signup successful')
        else:
            return JsonResponse(dict(form.errors.items()))
                
    else:
        form = RegisterForm()
    return render(request, "register/register.html", {'form': form, 'page': 'Sign Up'})

def signup_success(request):
    return render(request, 'register/signup_success.html')

def activate_account(request, uidb64, token):
    try:
        uid = force_bytes(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request,user)
        messages.success(request, 'Signup successful')
        return redirect('/dashboard/')
    return HttpResponse('Activation link is invalid!')

def login_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(settings.LOGIN_REDIRECT_URL)
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            return redirect('/dashboard/')
        messages.error(request,'Username or password not correct')
        return redirect('login')
    else:
        form = AuthenticationForm()
    return render(request, "register/login.html", {'form': form, 'next': settings.LOGIN_REDIRECT_URL })

def lgoin_superuser_view(request):
    if request.user.is_authenticated and request.user.is_superuser:
        return HttpResponseRedirect(settings.LOGIN_SUPERUSER_REDIRECT_URL)
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            if user.is_superuser:
                login(request,user)
                return redirect('/manage/')
            else:
                messages.error(request,'Permission denined')
                return redirect('login')
        else:
            messages.error(request,'Username or password not correct')
        return redirect('login_superuser')
    else:
        form = AuthenticationForm()
    return render(request, "register/login_superuser.html", {'form': form, 'next': settings.LOGIN_SUPERUSER_REDIRECT_URL, 'page': 'Log in' })


def logout_view(request):
    logout(request)
    return redirect(settings.LOGOUT_REDIRECT_URL)

def logout_superuser_view(request):
    logout(request)
    return redirect(settings.SUPREUSER_LOGOUT_REDIRECT_URL)

templates/register/activate_account.html
{% autoescape off %}
Hi {{ user.first_name }} {{ user.last_name }},
Thank you for registering to work with Vamux.
Your login username is: {{user.username}}
To complete your registration, please click the following link to verify your email:
http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %} 

templates/register/base.html
{% load static %}

<!DOCTYPE html>
<html class="no-js" lang="en">
    <head>
        <!-- Meta Tags -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="author" content="themexriver">
        <title>
            {% block title %}
                {% if page %}Vamux - {{ page }}{% endif %}
            {% endblock %}
        </title>

        {# Global stylesheets #}
        <!-- Favicon and Touch Icons -->
        <link href="{% static 'images/favicon.png' %}" rel="shortcut icon" type="image/png">
        <link href="{% static 'images/apple-touch-icon.png' %}" rel="apple-touch-icon">
        <link href="{% static 'images/apple-touch-icon-72x72.png' %}" rel="apple-touch-icon" sizes="72x72">
        <link href="{% static 'images/apple-touch-icon-114x114.png' %}" rel="apple-touch-icon" sizes="114x114">
        <link href="{% static 'images/apple-touch-icon-144x144.png' %}" rel="apple-touch-icon" sizes="144x144">

        <!-- Icon fonts -->
        <!-- <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet"> -->
        <script src="https://kit.fontawesome.com/74b77a9efd.js" crossorigin="anonymous"></script>
        <link href="{% static 'css/flaticon.css' %}" rel="stylesheet">

        <!-- Bootstrap core CSS -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

        <!-- Plugins for this template -->
        <link href="{% static 'css/animate.css' %}" rel="stylesheet">
        <link href="{% static 'css/owl.carousel.css' %}" rel="stylesheet">
        <link href="{% static 'css/owl.theme.css' %}" rel="stylesheet">
        <link href="{% static 'css/owl.transitions.css' %}" rel="stylesheet">
        <link href="{% static 'css/jquery.fancybox.css' %}" rel="stylesheet">
        <link href="{% static 'css/bootstrap-select.css' %}" rel="stylesheet">
        <link href="{% static 'css/magnific-popup.css' %}" rel="stylesheet">

        <!-- Custom styles for this template -->
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
        <link href="{% static 'css/custom.css' %}" rel="stylesheet">
        {% block extra_css %}
            {# Override this in templates to add extra stylesheets #}
        {% endblock %}
    </head>

    <body class="{% block body_class %}{% endblock %}">
        <div class="page-wrapper" id="home">
           
        {% block content %}{% endblock %}
        <!-- All JavaScript files
        ================================================== -->
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>

        <!-- Plugins for this template -->
        <script src="{% static 'js/jquery-plugin-collection.js' %}"></script>

        <!-- Custom script for this template -->
        <script src="{% static 'js/script.js' %}"></script>
        </div>
    </body>
</html>

templates/register/login.html
{% extends 'register/base.html' %}
{% load static widget_tweaks %}
{% block content %}
<section class="section-padding">
    <div class="container">
        <div class="col col-md-6 col-md-offset-3 register-form">
            <div class="p-15">
                <div class='main-title'>
                    <h1>
                        Log In 
                    </h1>
                </div>
                <div class="box">
                    {% for message in messages %}
                        <div class="alert alert-danger">
                            <a class="close" href="#" data-dismiss="alert">×</a>
                            {{ message }}
                        </div>
                    {% endfor %}
                    <form class="form pt-lg-5" id="login_form" action="{% url 'login' %}" method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="row pt-md-4">
                                <div class="col col-sm-4">
                                    {{field.label_tag}}
                                </div>
                                <div class="col col-sm-8">
                                    {{field|attr:"class:form-control"}}
                                </div>
                            </div>
                        {% endfor %}
                        <div class="row pt-md-4">
                            <div class="col col-sm-4">
                            </div>
                            <div class="col col-sm-8 submit-btn">
                                <button class="btn theme-btn-s2" style="width: 100%;" id="order_submit">Login</button>
                            </div>
                        </div>
                        <div class="row pt-md-4">
                            <div class="col col-sm-4">
                            </div>
                            <div class="col col-sm-8">
							    <span><a href="{% url 'password_reset' %}">Forget password?</a>/<a href="/account/register">Sign Up Here</a></span>
                            </div>
                        </div>                        
                    </form>
                </div>
            </div>
            
        </div>
    </div>

</section>

{% endblock %}

templates/register/login_superuser.html
{% extends 'register/base.html' %}
{% load static widget_tweaks %}
{% block content %}
<section class="section-padding">
    <div class="container">
        <div class="col col-md-6 col-md-offset-3 register-form">
            <div class="p-15">
                <div class='main-title'>
                    <h1>
                        Log In 
                    </h1>
                </div>
                <div class="box">
                    {% for message in messages %}
                        <div class="alert alert-danger">
                            <a class="close" href="#" data-dismiss="alert">×</a>
                            {{ message }}
                        </div>
                    {% endfor %}
                    <form class="form pt-lg-5" id="login_form" action="{% url 'login_superuser' %}" method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="row pt-md-4">
                                <div class="col col-sm-4">
                                    {{field.label_tag}}
                                </div>
                                <div class="col col-sm-8">
                                    {{field|attr:"class:form-control"}}
                                </div>
                            </div>
                        {% endfor %}
                        <div class="row pt-md-4">
                            <div class="col col-sm-4">
                            </div>
                            <div class="col col-sm-8 submit-btn">
                                <button class="btn theme-btn-s2" style="width: 100%;" id="order_submit">Login</button>
                            </div>
                        </div>               
                    </form>
                </div>
            </div>
            
        </div>
    </div>

</section>

{% endblock %}

templates/register/password_change.html
{% extends 'register/base.html' %}


{% block content %}

<form method="POST" class="form-control">
    {% csrf_token %}
    <h1> Change password</h1>
    <input name="old_password" class="form-control" placeholder="Old password" type="password" id="id_old_password" required>
    <input name="new_password1" class="form-control" placeholder="New password" type="password" id="id_new_password1" required>
    <input name="new_password2" class="form-control" placeholder="Confirm password" type="password" id="id_new_password2" required>

    {% for field in form %}
        {% for error in field.errors %}
            <p style="color: red;">{{error}}</p>
        {% endfor %}
    {% endfor %}

    <button class="btn btn-primary btn-block" type="submit">Update</button>
</form>

{% endblock %}

templates/register/password_change_done.html
{% extends 'register/base.html' %}
{% block content %}

<div class="container">
    <div class="row">
        <p class="">
            Your password has been set. You may go ahead and <a href="{% url 'login' %}">login</a>
            now.
        </p>
    </div>
</div>

{% endblock %}

templates/register/password_reset.html
{% extends 'register/base.html' %}
{% load static %}
{% block content %}
<section class="section-padding">
    <div class="container">
        <div class="col col-md-6 col-md-offset-3 register-form">
            <div class="p-15">
                <div class='main-title'>
                    <h1>
                        Password reset
                    </h1>
                </div>
                <div class="box">
                    <p>Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.</p>
                    <form class="form pt-lg-5" method="POST">
                        {% csrf_token %}
                            <div class="row pt-md-4">
                                <div class="col col-sm-4">
                                    <label for="">Email address:</label>
                                </div>
                                <div class="col col-sm-8">
                                    <input class="form-control" type="email" id="id_email" name="email" autocomplete="email" required>
                                </div>
                            </div>
                        <div class="row pt-md-4">
                            <div class="col col-sm-4">
                            </div>
                            <div class="col col-sm-8 submit-btn">
                                <button class="btn theme-btn-s2" style="width: 100%;" type="submit">Reset my password</button>
                            </div>
                        </div>                    
                    </form>
                </div>
            </div>
            
        </div>
    </div>

</section>

{% endblock %}

templates/register/password_reset_complete.html
{% extends 'register/base.html' %}
{% block content %}

    <section class="section-padding">
        <div class="container">
            <div class="col col-md-6 col-md-offset-3 register-form">
                <div class="p-15">
                    <div class="box">
                        <p>
                            Your password has been reset. You may go ahead and <a href="{% url 'login' %}" style="display: initial !important;">login</a>
                            now.
                        </p>
                    </div>
                </div>
                
            </div>
        </div>
    
    </section>
{% endblock %}

templates/register/password_reset_done.html
{% extends 'register/base.html' %}
{% block content %}
    <section class="section-padding">
        <div class="container">
            <div class="col col-md-6 col-md-offset-3 register-form">
                <div class="p-15">
                    <div class="box">
                        <p>
                            We've emailed you instructions for setting your password, if an account exists with the
                            email you entered.
                            You should receive them shortly.
                        </p>
                        <p>
                            If you don't receive an email, please make sure you've entered the address you registered
                            with,
                            and check your spam folder.
                        </p>
                        <p>
                            <a href="{% url 'home' %}">
                                Return to home page
                            </a>
                        </p>
                    </div>
                </div>
                
            </div>
        </div>
    
    </section>
{% endblock %}

templates/register/password_reset_email.html
{% autoescape off %}

    To initiate the password reset process for your Account {{ user.email }},
    click the link below:

    {{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uid64=uid token=token %}

    If clicking the link above doesn't work, please copy and paste the URL in a new browser
    instead.

    Sincerely,
    The Vamux Support team

{% endautoescape %}

templates/register/password_reset_form.html
{% extends 'register/base.html' %}
{% block content %}

<section class="section-padding">
    <div class="container">
        <div class="col col-md-6 col-md-offset-3 register-form">
            <div class="p-15">
                <div class='main-title'>
                    <h1>
                        Enter new password
                    </h1>
                </div>
                <div class="box">
                    <p>Please enter your new password twice so we can verify you typed it in correctly.</p>
                    <form class="form pt-lg-5" method="POST">
                        {% csrf_token %}
                            
                            <div class="row pt-md-4">
                                <div class="col col-sm-4">
                                    <label for="">New password:</label>
                                </div>
                                <div class="col col-sm-8">
                                    <input class="form-control" type="password" id="id_new_password1" name="new_password1" autocomplete="new-password" required>
                                </div>
                            </div>
                            <div class="row pt-md-4">
                                <div class="col col-sm-4">
                                    <label for="">Confirm password:</label>
                                </div>
                                <div class="col col-sm-8">
                                    <input class="form-control" type="password" id="id_new_password2" name="new_password2" autocomplete="new-password" required>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col col-sm-4">

                                </div>
                                <div class="col col-sm-8">
                                    {% for field in form %}
                                    {% for error in field.errors %}
                                        <p style="color: red;">{{error}}</p>
                                    {% endfor %}
                                {% endfor %}
                                </div>
                            </div>
                        <div class="row pt-md-4">
                            <div class="col col-sm-4">
                            </div>
                            <div class="col col-sm-8 submit-btn">
                                <button class="btn theme-btn-s2" style="width: 100%;" type="submit">Change my password</button>
                            </div>
                        </div>                    
                    </form>
                </div>
            </div>
            
        </div>
    </div>

</section>

{% endblock %}

templates/register/register.html
{% extends 'register/base.html' %}
{% load static widget_tweaks %}

{% block content %}
<section class="section-padding">
    <div class="container">
        <div class="col col-md-6 col-md-offset-3 register-form">
            <div class="p-15">
                <div class='main-title'>
                    <h1>
                        Sign Up
                    </h1>
                </div>
                <div class="">
                    <form class="form pt-lg-5 sign_up_form" id="registration_form">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="row pt-md-4 form-element">
                                <div class="col col-sm-5">
                                    *{{field.label_tag}}
                                </div>
                                <div class="col col-sm-7">
                                    {{field|attr:"class:form-control"}}
                                </div>
                            </div>
                        {% endfor %}
                        <!-- {{ form.as_p }} -->
                        <div class="row pt-md-4">
                            <div class="col col-sm-5">
                            </div>
                            <div class="col col-sm-7">
                                <input type="checkbox" class="checkbox" required>
							    <span>I Agree To The <a href="https://vamux.com/terms-and-conditions/" target="_blank">Terms & Conditions</a></span>
                            </div>
                        </div>
                        <div class="row pt-md-4 error-message">
                        </div>
                        <div class="row pt-md-4">
                            <div class="col col-sm-5">
                            </div>
                            <div class="col col-sm-7 submit-btn">
                                <button class="btn theme-btn-s2 buttonload" id="order_submit">
                                    <i class="fa fa-spinner fa-spin" style="display: none;"></i>
                                    SignUp
                                </button>
                            </div>
                        </div>
                        <div class="row pt-md-4">
                            <div class="col col-sm-5">
                            </div>
                            <div class="col col-sm-7">
							    <span>Already have an account? <a href="/account/login">Login Here</a></span>
                            </div>
                        </div>                        
                    </form>
                </div>
                <div class="pt-lg-5" id="signup_success" style="display: none;">
                    <h3>
                        Welcome to Vamux.com
                    </h3>
                    <p>
                        We have sent you an email, please confirm your email address to complete registration
                    </p>
                    <a href="/account/login/">Go to Login page</a>
                </div>
            </div>
        </div>
    </div>

</section>
{% endblock %}

templates/register/signup_success.html
{% extends 'register/base.html' %}
{% load static widget_tweaks %}

{% block content %}
<section class="section-padding">
    <div class="container">
        <div class="col col-md-6 col-md-offset-3 p-15">
            <div class="pt-lg-5" id="signup_success" style="display: none;">
                <h3>
                    Welcome to Vamux.com
                </h3>
                <p>
                    We have sent you an email, please confirm your email address to complete registration
                </p>
                <a href="/account/login/">Go to Login page</a>
            </div>
        </div>
    </div>
</section>
{% endblock %}